language: python

python:
  - "3.6"
  - "3.7"

install:
  - pip install -r Deities/tools/requirements.txt
  - pip install -r Grobber/requirements.txt

script:
  - pytest --cov-config .coveragerc --cov=./

after_success:
  - codecov