language: python

python:
  - "3.6"

install:
- pipenv install --dev
  - pip install codecov
  - pip install pytest pytest-cov

script:
  - pytest --cov-config .coveragerc --cov=./

after_success:
  - codecov