version: "3"

services:
  app:
    container_name: MyAnimeStream
    build: .
    image: myanimestream
    restart: always
    ports:
      - 80:80
    networks:
      - backend
    environment:
      - MONGO_URI=mongodb://database:27017
      - HTTP_PROXY=http://proxy:8081
      - HTTPS_PROXY=http://proxy:8081
      - SENTRY_DSN
    depends_on:
      - database

  database:
    container_name: MongoDB
    image: mongo
    restart: always
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - database:/data/db
    networks:
      - backend

  proxy:
    container_name: Scylla
    image: siku2/scylla:latest
    restart: always
    ports:
      - 8899:8899
      - 8081:8081
    expose:
      - 8081
    volumes:
      - scylla:/var/www/scylla
    networks:
      - backend

volumes:
  database: {}
  scylla: {}

networks:
  backend: {}