version: "3"

services:
  app:
    container_name: MyAnimeStream
    build: .
    image: myanimestream
    restart: always
    ports:
      - 80:80
    networks:
      - backend
    environment:
      - MONGO_URI=mongodb://database:27017
      - CHROME_WS=ws://browserless:3000
      - PROXY_URL=http://proxy:8081
      - SENTRY_DSN
    depends_on:
      - database
      - proxy
      - browserless

  database:
    container_name: MongoDB
    image: mongo
    restart: always
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - database:/data/db
    networks:
      - backend

  proxy:
    container_name: Scylla
    image: siku2/scylla:latest
    restart: always
    ports:
      - 8899:8899
      - 8081:8081
    expose:
      - 8081
    volumes:
      - scylla:/var/www/scylla
    networks:
      - backend

  browserless:
    container_name: Browserless
    image: browserless/chrome
    restart: always
    environment:
      - MAX_CONCURRENT_SESSIONS=5
      - MAX_QUEUE_LENGTH=10
      - PREBOOT_CHROME=true
      - CONNECTION_TIMEOUT=300000
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - backend

volumes:
  database: {}
  scylla: {}

networks:
  backend: {}